
1、创建数据库本地用户test，密码为oracle，默认表空间为users，临时表空间为temp，同时具有create session系统权限。

CREATE USER TEST
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO TEST;
REVOKE CREATE SESSION FROM TEST;

GRANT CONNECT TO TEST;
REVOKE CONNECT FROM TEST;
GRANT RESOURCE TO TEST;
REVOKE RESOURCE FROM TEST;

2、用户王明对两个表有SELECT权力；

CREATE USER 王明
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO 王明;

GRANT SELECT ON hr.职工 TO 王明;
GRANT SELECT ON hr.部门 TO 王明;
REVOKE SELECT ON hr.职工 FROM 王明;
REVOKE SELECT ON hr.部门 FROM 王明;


3、用户李勇对两个表有INSERT和DELETE权力；

CREATE USER 李勇
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO 李勇;

GRANT INSERT ON hr.职工 TO 李勇;
GRANT INSERT ON hr.部门 TO 李勇;
REVOKE INSERT ON hr.职工 FROM 李勇;
REVOKE INSERT ON hr.部门 FROM 李勇;

GRANT DELETE ON hr.职工 TO 李勇;
GRANT DELETE ON hr.部门 TO 李勇;
REVOKE DELETE ON hr.职工 FROM 李勇;
REVOKE DELETE ON hr.部门 FROM 李勇;

4、用户刘星对职工表有SELECT权力，对工资字段具有更新权力；

DROP USER 刘星 CASCADE;

CREATE USER 刘星
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO 刘星;

GRANT SELECT ON hr.职工 TO 刘星;
REVOKE SELECT ON hr.职工 FROM 刘星;
GRANT UPDATE(工资) ON hr.职工 TO 刘星;
REVOKE UPDATE (工资) ON hr.职工 FROM 刘星;

5、用户周平具有对两个表所有权力（读、插、改、删数据），并具有给其他用户授权的权力；
提示：所有权力为ALL PRIVILEGE，在GRANT语句中使用WITH GRANT OPTION选项，被授权的用户就具有了再次将对象权限授予其他用户的能力。

DROP USER 周平 CASCADE;

CREATE USER 周平
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO 周平;

GRANT ALL PRIVILEGES ON hr.部门 TO 周平 WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON hr.职工 TO 周平 WITH GRANT OPTION;

6、用户杨兰具有从每个部门职工中SELECT最高工资，最低工资，平均工资的权力，他不能查看每个人的工资。
提示：首先创建视图查询每个部门职工中的最高工资，最低工资和平均工资，然后授予用户查询视图的权限。

CREATE USER 杨兰
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO 杨兰;

CREATE VIEW 职工_工资(部门号,平均工资,最高工资,最低工资) AS
SELECT 部门号,AVG(工资),MAX(工资),MIN(工资) FROM hr.职工
GROUP BY 部门号;

SELECT * FROM 职工_工资
DROP VIEW 职工_工资;


GRANT SELECT ON 职工_工资 TO 杨兰;
REVOKE SELECT ON 职工_工资 FROM 杨兰;



三、设计安全机制使得用户“liming”只能查询年龄在40岁以上（包括）职工。
提示：用视图实现

CREATE USER LIMING
IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO LIMING;

CREATE VIEW 职工_年龄(职工号,姓名,年龄) AS
SELECT 职工号,姓名,年龄 FROM hr.职工
WHERE 年龄 >= 40;

SELECT * FROM 职工_年龄
DROP VIEW 职工_年龄;


GRANT SELECT ON 职工_年龄 TO LIMING;
REVOKE SELECT ON 职工_年龄 FROM LIMING;




四、设计安全机制使得用户“liming”只能访问“职工”的职工号、姓名。
提示：用视图实现

CREATE VIEW 职工_姓名(职工号,姓名) AS
SELECT 职工号,姓名 FROM hr.职工;

SELECT * FROM 职工_姓名
DROP VIEW 职工_姓名;


GRANT SELECT ON 职工_姓名 TO LIMING;
REVOKE SELECT ON 职工_姓名 FROM LIMING;


五、设计角色“student”，可以查看“职工”的职工号、姓名、年龄。将用户“liming”添加到角色“student”中。
提示：用视图实现

CREATE ROLE STUDENT;

CREATE VIEW 职工_角色 AS
SELECT 职工号,姓名,年龄 FROM hr.职工;

GRANT SELECT ON hr.职工_角色 TO SUTDENT;

CREATE ROLE STUDENT;

GRANT STUDENT TO LIMING;
