CREATE TABLE S(
SNO CHAR(10) PRIMARY KEY,
SNAME CHAR(10) NOT NULL,
CITY CHAR(10)
);

CREATE TABLE P(
PNO CHAR(10) PRIMARY KEY,
PNAME CHAR(10) NOT NULL,
COLOR CHAR(10) CHECK(
COLOR IN ('RED','BLUE','GREEN'))
);

CREATE TABLE J(
JNO CHAR(10) PRIMARY KEY,
JNAME CHAR(10) NOT NULL
);

CREATE TABLE SPJ(
SNO CHAR(10),
PNO CHAR(10),
JNO CHAR(10),
PRIMARY KEY(SNO,PNO,JNO),
FOREIGN KEY(SNO) REFERENCES S(SNO),
FOREIGN KEY(PNO) REFERENCES P(PNO),
FOREIGN KEY(JNO) REFERENCES J(JNO),
QTY CHAR(10) CHECK (QTY > 0 AND QTY < 1000)
);

INSERT INTO S(SNO) VALUES('');

INSERT INTO P(PNO,PNAME) VALUES('P','PP');

INSERT INTO P(PNO) VALUES('P');

INSERT INTO P(COLOR) VALUES('WIGHT');

INSERT INTO S(SNO) VALUES('');

INSERT INTO SPJ(MNO) VALUES('');

ALTER TABLE SPJ
ADD SNO VALUES('')

ALTER TABLE SPJ
DROP P

CREATE TABLE SPJ1(
SNO CHAR(10),
PNO CHAR(10),
JNO CHAR(10),
PRIMARY KEY(SNO,PNO,JNO),
FOREIGN KEY(SNO) REFERENCES S(SNO),
FOREIGN KEY(PNO) REFERENCES P(PNO),
FOREIGN KEY(JNO) REFERENCES J(JNO)
);

ALTER TABLE SPJ1
DROP QNO

ALTER TABLE P
DROP PNO

ALTER TABLE P1
UPDATE P1NO

ALTER TABLE P
UPDATE PNO
